name: Deploy React (Vite) to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Needed so the action can push to gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        shell: bash
        run: |
          # If deploying to <user>.github.io, base should be '/'; otherwise '/<repo>/'
          if [[ "$REPO_NAME" == *.github.io ]]; then
            npm run build -- --base=/
          else
            npm run build -- --base="/$REPO_NAME/"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
